# Generated by Django 5.0.6 on 2024-07-04 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_products_disocont_alter_products_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='disocont',
            new_name='discount',
        ),
    ]
