# Generated by Django 5.0.6 on 2024-07-10 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0004_alter_categories_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date of order creation')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone number')),
                ('requires_delivery', models.BooleanField(default=False, verbose_name='Does delivery requires')),
                ('delivery_address', models.TextField(blank=True, null=True, verbose_name='Delivery address')),
                ('payment_on_get', models.BooleanField(default=False, verbose_name='Payment on place')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Paid')),
                ('satus', models.CharField(default='In process', max_length=50, verbose_name='Order status')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('product', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='goods.products')),
            ],
            options={
                'verbose_name': 'Sold item',
                'verbose_name_plural': 'Sold items',
                'db_table': 'order_item',
            },
        ),
    ]
